version: '3'

services:
 module:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   volumes: ["./module:/opt/module"]
   environment:
     PORT: "5005"
     FLASK_DEBUG: "true"
   ports:
     - "5005:5005"
